# Generated by Django 4.1.3 on 2022-12-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='local',
            new_name='sucursal',
        ),
    ]
